<?php
// Heading
$_['heading_title']      = 'Tickets';

// Text
$_['text_info']          = 'These tickets are generated by your account.';

$_['entry_type']      = 'Type';
$_['entry_tags']     	= 'Tags';
$_['entry_date_added']     	= 'Date Added';

$_['text_view_ticket'] = 'Ticket ';
$_['text_list_tickets']   = 'All Ticket(s)';
$_['text_ticket_subject']   = 'Subject';
$_['text_ticket_type']   = 'Type';
$_['text_ticket_priority']   = 'Priority';
$_['text_ticket_status']   = 'Status';
$_['text_ticket_group']   = 'Group';
$_['text_ticket_requester']   = 'Requester';
$_['text_ticket_created']   = 'Created';
$_['text_assign_to_agent']       = 'Assigned To Agent';
$_['text_column_name']       = 'Name';
$_['text_column_order']       = 'Order';

$_['text_id']            = 'Ticket Id';
$_['text_basic_id']            = 'Id';
$_['text_ask']            = 'Ask Query';
$_['text_system']       = 'System';

$_['text_min']      = 'Min';
$_['text_hours']      = 'Hours';
$_['text_days']       = 'Days';
$_['text_month']      = 'Months';
$_['text_web']      = 'Website';
$_['text_mail']      = 'Email';
$_['text_everyone']      = 'Every One';
$_['text_any']      = 'Any';
$_['text_from']      = 'From';
$_['text_to']      = 'To';
$_['text_created']      = 'Created';
$_['text_updated']      = 'Updated';
$_['text_deleted']      = 'Deleted';
$_['text_unassigned']      = 'UnAssigned';
$_['text_sort']      = 'Sorting';
$_['text_customer']   = 'Customer';
$_['text_customer_details']   = 'Customer Details';
$_['text_previous']   = 'Previous';
$_['text_next']   = 'Next';
$_['text_cc']   = 'Cc';
$_['text_coma_separated']   = ' , separated';
$_['text_bcc']   = 'Bcc';
$_['text_more_expand']   = 'More Expand';
$_['text_displayed_all']   = 'Displayed All';
$_['text_asked']   = 'asked';
$_['text_wrote']   = 'wrote';
$_['text_print']   = 'Print';

$_['text_customer_replied']   = '%s <b class="text-danger">asked</b> on %s';
$_['text_agent_replied']   = '%s <b class="text-success">replied</b> on %s';
$_['text_agent_forwarded']   = '%s <b class="text-primary">forwarded</b> on %s';
$_['text_agent_added_note']   = '%s <b class="text-warning">added note</b> on %s';

$_['text_no_results']   = 'No Results Found !!';
$_['text_disable']   = 'Disable';
$_['text_enable']   = 'Enable';
$_['text_please_wait']   = 'Please Wait ..';
$_['text_fileupload']   = 'Upload File';
$_['text_fileupload_info']   = 'Click to Upload File(s) (Max - %d), Max File Size - %d KB';

$_['text_confirm']   = 'Are you sure ?';

$_['closed_ticket_status']  = 'Ticket status is closed !!';
$_['spam_ticket_status']  = 'Ticket status is SPAM !!';

$_['button_clrfilter']  = 'Clear';
$_['button_remove']   = 'Remove';
$_['button_reply']   = 'Reply';
$_['button_forward']   = 'Forward';
$_['button_delete_ticket']    = 'Delete Ticket';
$_['button_close_ticket']    = 'Close Ticket';
$_['button_apply']    = 'Apply';

$_['text_success']    = 'Success ! you have been successfully deleted Ticket(s).';
$_['text_success_closed_ticket']    = 'Success ! you have been successfully closed Ticket %s.';
$_['text_success_delete_thread']    = 'Success ! you have been successfully delete Ticket Thread.';
$_['text_success_apply_action']    = 'Success ! you have been successfully applied response to ticket.';
$_['text_success_reply']    = 'Success ! you have been successfully asked your query.';

$_['error_message']  = 'Warning ! Please add message to reply.';
$_['error_access_permission']  = 'Warning ! You do not have permission to perform this task.';
$_['error_too_much_images']  = 'Warning ! Files are more than allowed no.';
$_['error_warning']  = 'Warning ! Please resolve all issues first.';
